language: scala

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - sbt test $(if [[ "${TRAVIS_REPO_SLUG}" == "msgpack4z/msgpack4z-java" && ${JAVA_HOME} == $(jdk_switcher home oraclejdk8) && "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

env:
  global:
  - secure: "PjOJ2wqcahHR0LZpTwjQhOdLaJ46byApesCzcVmWjCsBg5stVCFs1EE6FhINi7/kwbX/WSrnjZB6vP4VVMlKL9T7A3X2ZZjcPZ/Smz6t+8A/Qm9rfZ9ookTDB2TM4qVdLamQHLMuAbWJzA/ydJndH7ODRow8UO1JHJo+N1LEwrzFFuWF4/vNljM3zDnFCCMc1uWgc3dmCnmsXafhamZ1AVZx3oDNw7ilRCsJQdI28t3A6upBnRbl35/1lHc23pfVGHxueNYPwxmovs/ELvzFURPY8+VCs+Wx4lQmPKcyw3/5ZjfyROLcSbTutXdhRLeFHLQ3+21yz1Tiemi4Ns/Klq1n5DAGqp79dSIwmXBC/mA/FJKEOAlPiF3UthxisQCb+l4PfzCd+UK9qTfJrvwcfYmqD14Ru8N6WgSoAU0g9ij3kwEQUDbjt9KymxJBJa6X2XkgTpP9o6+tMzhiWzW/Rocq7vgWL6VvXYZ7J9cneNCccsOcT7AqpHCLm0BwkVImZdWSXKw//pmTVrsTI4RWcfCqoa5Tb5BP9tdeJNnXxuM6aWev5twQrPN0pD9JfqSJxwSyn+vwozIlZR5fBUoBZObLmxE79zLhtXnGhO0rAgkHLEEfstsTmJ2viZXX5zRBEk7ZbyznLajU80TREPFqqYkVRQQT0rRjperj2OVVmas="
  - secure: "YpBd0bIt4LCPo+a062PFP1KD7vDl8bsN4QIWMCNdCr0w8bn/EDp5koRKVsMuEUXgU171A/8yy4oIcIm7FXVy6cVyCx84M2q194NuioFk5pr6ZUghplK5sH0006wZk+oh/qOhmLaHZtSzk+DoFFeav4Wu78np/AtBF5gu3KeLjnxsIVwjkaMFR1HONInjN1g1593/RT8fCGdoKPUgl02BMk5YiCK54bfvP5UQLs3Ja9xHZ8rqtZ+iXXSOVJtXOEYhy2APZe6u6sl7kFURI9JBH3/YI+F8xmCJHEzYTSxlt19NP//21QyW4snbH2MzKZs7+GJpRZWMlWVflUKMehX74o1EoCLRsdSM78QRIxASSHjHGyC5eALXVFAZuZZnLF6lRFppfV9sM/t+WEOwnYyLVDlwdhxaTETnJtq+AG3vcY1tiCwPvB5XEL4K5FdGZHYnyTTGZ2FjozWEFS8vcWFfRoXU2629lQtiKqA5YjW/22tYeWCBPahBLdsvToe2ELF5hXSgYa4cbewx55qJH2amh4Wb9UDjw6dxmJdWIDiQ4xPrWzI/NXnPKFpGbjWf4D/Pr30kLPZyprGnkdOjDULWBemF3PDPWThZLTBquL+8tkMdTG88sIh09dktnnV9w+P5R9BUOPcklnbW7ZwbN3JThGJZAIiCmCS10jxJHTjGFPE="
